name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - Test
      - release/**

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build
          echo "Build completed successfully"

      - name: Prepare SPA files (404 fallback and disable Jekyll)
        working-directory: frontend
        run: |
          # Ensure SPA routing works by providing a 404 fallback
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
            echo "Created 404.html for SPA routing"
          fi
          # Disable Jekyll processing on GitHub Pages which can 404 static files
          touch dist/.nojekyll
          echo "Created .nojekyll file"

      - name: Debug - List build output
        working-directory: frontend
        run: |
          echo "=== Dist directory contents ==="
          ls -laR dist/
          echo ""
          echo "=== Checking for required files ==="
          test -f dist/index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
          test -f dist/.nojekyll && echo "✓ .nojekyll exists" || echo "✗ .nojekyll missing"
          test -f dist/404.html && echo "✓ 404.html exists" || echo "✗ 404.html missing"
          test -d dist/assets && echo "✓ assets directory exists" || echo "✗ assets directory missing"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
