name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
      - master
      - release/**
      - 'refs/heads/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Prepare SPA files (404 fallback and disable Jekyll)
        working-directory: frontend
        run: |
          # Ensure SPA routing works by providing a 404 fallback
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          fi
          # Disable Jekyll processing on GitHub Pages which can 404 static files
          touch dist/.nojekyll

      - name: Debug: show dist contents
        working-directory: frontend
        run: |
          echo "Dist contents:" && ls -la dist || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
